esphome:
  name: ${devicename}
  platform: ESP32
  board: mhetesp32minikit

# Wifi settings
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

captive_portal:

# Enable logging
# logger:
#   level: DEBUG

# Enable Home Assistant API
api:

# Enable over the air updates
ota:

# Enable Web server
web_server:
  port: 80

status_led:
  pin: GPIO2

switch:
  - platform: gpio
    pin: GPIO17
    name: blink

# Example configuration entry
uart:
  id: uart_sml
  rx_pin: GPIO16
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

sml:
  id: smlid
  uart_id: uart_sml
